Update deploy_arm_template.yml

diff --git a/.github/workflows/deploy_arm_template.yml b/.github/workflows/deploy_arm_template.yml
--- a/.github/workflows/deploy_arm_template.yml
+++ b/.github/workflows/deploy_arm_template.yml
@@ -40,12 +40,19 @@ jobs:
         PRE_SCRIPT_ARGUMENT: ${{ github.event.client_payload.preScriptArgument }}
       if: ${{ github.event.client_payload.preScriptLocation != null && endsWith(github.event.client_payload.preScriptLocation, '.sh') }}
       run: |
-        ls -la
-        chmod +x $PRE_SCRIPT_LOCATION
-        if [[ -z $PRE_SCRIPT_ARGUMENT ]]; then
-          bash $PRE_SCRIPT_LOCATION
+        pwd
+        ls -la .
+        ls -la ..
+        if [[ -f $PRE_SCRIPT_LOCATION ]]; then
+          chmod +x $PRE_SCRIPT_LOCATION
+          if [[ -z $PRE_SCRIPT_ARGUMENT ]]; then
+            bash $PRE_SCRIPT_LOCATION
+          else
+            bash $PRE_SCRIPT_LOCATION $PRE_SCRIPT_ARGUMENT
+          fi
         else
-          bash $PRE_SCRIPT_LOCATION $PRE_SCRIPT_ARGUMENT
+          echo "[$PRE_SCRIPT_LOCATION] script file not found"
+          exit 1
         fi
     - name: Azure Resource Manager (ARM) Template Deployment JS
       uses: whiteducksoftware/azure-arm-action-js@v3
